### ISSUE TITLE
Const declaration repeated in inventory.js 

### ISSUE THREAD

**Issue by quovai** [tngoman/Store-POS#2]
Lines:

const Datastore = require( "nedb" );
const async = require( "async" )

should be removed?

const Datastore = require( "nedb" );
      ^

SyntaxError: Identifier 'Datastore' has already been declared
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (F:\dati\personale\web\001-booking\store-pos\server.js:32:27)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)

**Comment by tngoman** [comment]
Yes, the duplicate declarations should be removed:

const Datastore = require( "nedb" );
const async = require( "async" )

**Comment by tngoman** [comment]
Removed.

**Comment by Kamalmazin** [comment]
> Lines:
> 
> const Datastore = require( "nedb" ); const async = require( "async" )
> 
> should be removed?
> 
> const Datastore = require( "nedb" ); ^
> 
> SyntaxError: Identifier 'Datastore' has already been declared at Module._compile (internal/modules/cjs/loader.js:722:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10) at Module.load (internal/modules/cjs/loader.js:645:32) at Function.Module._load (internal/modules/cjs/loader.js:560:12) at Module.require (internal/modules/cjs/loader.js:685:19) at require (internal/modules/cjs/helpers.js:16:16) at Object. (F:\dati\personale\web\001-booking\store-pos\server.js:32:27) at Module._compile (internal/modules/cjs/loader.js:786:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10) at Module.load (internal/modules/cjs/loader.js:645:32)
